# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  usersapi:
    image: usersapi
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=8001
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8081:80"
      - "8001:443"
    volumes:
      - ${APPDATA}\microsoft\UserSecrets\:/root/.microsoft/usersecrets
      - ${USERPROFILE}\.aspnet\https:/root/.aspnet/https/

  sqldata:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - SA_PASSWORD=Numsey#2022Passw00rd
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
